name: Makefile CI (Francinette)

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'
        
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y gcc make libbsd-dev python3-pip git python3-venv

    - name: Install Francinette (official method)
      run: |
        # Run installer non-interactively
        curl -fsSL https://raw.github.com/xicodomingues/francinette/master/bin/install.sh | bash -s -- -y
        
        # Add to PATH
        echo "$HOME/francinette/bin" >> $GITHUB_PATH
        echo "$HOME/.local/bin" >> $GITHUB_PATH
        
        # Verify installation
        ls -la $HOME/francinette/bin/francinette
        ls -la $HOME/francinette/venv/bin/python

    - name: Run Francinette
      run: |
        # Use the installed wrapper
        $HOME/francinette/bin/francinette --version
        $HOME/francinette/bin/francinette .
