name: Makefile CI (Francinette)

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'
        
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y gcc make libbsd-dev python3-pip git python3-venv

    - name: Install Francinette
      run: |
        python3 -m venv venv
        . venv/bin/activate

        pip install wheel setuptools

        pip install --no-cache-dir --timeout 100 git+https://github.com/xicodomingues/francinette.git

        pip show francinette

    - name: Run Francinette
      run: |
        . venv/bin/activate
        python -c "from francinette import main; main()" --version
        python -c "from francinette import main; main()" .
