name: Francinette CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y gcc make libbsd-dev python3-pip git python3-venv
        sudo apt-get install -y python3.12-full

    - name: Install Francinette with fix
      run: |
        git clone https://github.com/xicodomingues/francinette.git ~/francinette
        
        sed -i "s/from pipes import quote/from shlex import quote/g" ~/francinette/testers/libft/Fsoares.py
        
        python3 -m venv ~/francinette/venv
        source ~/francinette/venv/bin/activate
        
        pip install wheel
        pip install -r ~/francinette/requirements.txt

    - name: Run Francinette
      run: |
        ~/francinette/venv/bin/python -c "from francinette import main; main()" --version
        ~/francinette/venv/bin/python -c "from francinette import main; main()" .
